services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data:/data/db
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q
        "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  authapi:
    image: authapi
    build:
      context: .
      dockerfile: src/AuthAPI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=${DB_DATABASE};User=sa;Password=${SA_PASSWORD};MultipleActiveResultSets=true;Encrypt=false
    volumes:
      - ./https:/https/
    depends_on:
      mssql:
        condition: service_healthy

  eduapi:
    image: eduapi
    build:
      context: .
      dockerfile: src/EduAPI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=${DB_DATABASE};User=sa;Password=${SA_PASSWORD};MultipleActiveResultSets=true;Encrypt=false
    volumes:
      - ./https:/https/
    depends_on:
      mssql:
        condition: service_healthy

  web:
    image: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=${DB_DATABASE};User=sa;Password=${SA_PASSWORD};MultipleActiveResultSets=true;Encrypt=false
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:48000;https://+:48443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ReverseProxy__Clusters__auth__Destinations__destination1__Address=http://authapi:8080
      - ReverseProxy__Clusters__EduApi__Destinations__destination1__Address=http://eduapi:8080
    ports:
      - "48000:48000"
      - "48443:48443"
    volumes:
      - ./https:/https/
    depends_on:
      - authapi
      - eduapi


volumes:
  mssql-data: